---
sudo: required
language: python
services:
  - docker

before_install:
  - sudo apt-get -qq update

  # stop unneeded services to free up build VM resources
  - sudo service mysql stop
  - sudo service neo4j stop
  - sudo service postgresql stop

install:
  - pip install tox-travis
  - pip install -r requirements.txt

script:
  - tox

notifications:
  webhooks: https://galaxy.ansible.com/api/v1/notifications/
