---

- name: install curl if needed
  package:
    name: curl
    state: present
    update_cache: true

- name: run RedHat specific tasks
  include: tasks-RedHat.yml
  when: ansible_os_family == 'RedHat'
  tags:
    - gitlab_runner
    - redhat

- name: run Debian specific tasks
  include: tasks-Debian.yml
  when: ansible_os_family == 'Debian'
  tags:
    - gitlab_runner
    - debian

- name: Install gitlab-runner
  package:
    name: gitlab-runner
    state: "{{ gitlab_runner_state }}"
  register: install_gitlab_runner
  until: install_gitlab_runner is succeeded
  tags:
    - gitlab_runner

- name: Set concurrent option
  lineinfile:
    dest: /etc/gitlab-runner/config.toml
    regexp: ^concurrent =
    line: concurrent = {{ ansible_processor_cores|default(2, true) }}
    state: present
    mode: 0644

- name: ensure directory for root
  file:
    path: /etc/gitlab-runner/certs/
    state: directory
    owner: root
    mode: 0755
  tags:
    - gitlab_runner
    - register_runner

- name: copy certificate for root
  when:
    - gitlab_host is defined
    - gitlab_transport == 'https'
  copy:
    src: "certs/{{ gitlab_host }}.crt"
    dest: "/etc/gitlab-runner/certs/"
    owner: root
    mode: 0644
  tags:
    - gitlab_runner
    - register_runner

- name: add docker_users to docker group
  user:
    name: "{{ item }}"
    groups: docker
    append: true
  when: docker_users is defined
  with_items: "{{ docker_users }}"
  ignore_errors: true
  tags:
    - gitlab_runner

- name: ensure directory for gitlab-runner
  file:
    path: /home/gitlab-runner/.gitlab-runner
    state: directory
    owner: gitlab-runner
    mode: 0751
  tags:
    - gitlab_runner
    - register_runner

- name: ensure directory for gitlab-runner
  when: gitlab_transport == 'https'
  file:
    path: /home/gitlab-runner/.gitlab-runner/certs
    state: directory
    owner: gitlab-runner
    mode: 0751
  tags:
    - gitlab_runner
    - register_runner

- name: copy certificate for gitlab-runner
  when:
    - gitlab_host is defined
    - gitlab_transport == 'https'
  copy:
    src: "certs/{{ gitlab_host }}.crt"
    dest: "/home/gitlab-runner/.gitlab-runner/certs/"
    owner: gitlab-runner
    mode: 0644
  tags:
    - gitlab_runner
    - register_runner

- name: List configured runners
  command: gitlab-runner list
  register: configured_runners
  changed_when: false
  tags:
    - gitlab_runner
    - register_runner

# yamllint disable rule:line-length
- name: register docker runner
  when: gitlab_external_url is defined and docker_runner|bool
  command: |
    gitlab-ci-multi-runner register \
    --non-interactive \
    --url "{{ gitlab_external_url }}" \
    --registration-token "{{ gitlab_runner_token }}" \
    --description "docker-runner" \
    --executor "docker" \
    --docker-network-mode="host" \
    --docker-tlsverify=false \
    --docker-privileged \
    --tag-list "{{ ansible_distribution|lower }}{{ ansible_distribution_major_version }},docker" \
    --docker-image='{{ gitlab_runner_image |default('alpine') }}'
  ignore_errors: true
  tags:
    - gitlab_runner
    - docker_runner
    - register_runner
    - skip_register

- name: register shell runner
  when: gitlab_external_url is defined and shell_runner|bool
  command: |
    gitlab-ci-multi-runner register \
    --non-interactive \
    --url "{{ gitlab_external_url }}" \
    --registration-token "{{ gitlab_runner_token }}" \
    --description "shell-runner" \
    --tag-list "{{ ansible_distribution|lower }}{{ ansible_distribution_major_version }},shell" \
    --executor "shell"
  ignore_errors: true
  tags:
    - gitlab_runner
    - shell_runner
    - register_runner
    - skip_register

- name: copy goss test template
  template:
    src: test_gitlabrunner.yml
    dest: /root/test_gitlabrunner.yml
    mode: 0644
  tags:
    - gitlab_runner
