---

- name: install Gitlab runner on linux
  include_tasks: linux.yml
  when: ansible_os_family != 'Windows'

- name: install Gitlab runner on windows
  include_tasks: windows.yml
  when: ansible_os_family == 'Windows'
