---

- name: Interpolate gitlab_external_url
  when:
    - gitlab_transport is defined
    - gitlab_host is defined
    - gitlab_port is defined
  set_fact:
    # yamllint disable-line rule:line-length
    gitlab_external_url: "{{ gitlab_transport }}://{{ gitlab_host }}:{{ gitlab_port }}/"

- name: Obtain registration token from gitlab in docker
  when:
    - gitlab_host is defined
    - gitlab_runner_token is not defined
  delegate_to: "{{ gitlab_host }}"
  become: true
  # yamllint disable-line rule:line-length
  command: 'docker exec -t gitlab gitlab-rails runner -e production "puts Gitlab::CurrentSettings.current_application_settings.runners_registration_token"'
  register: runners_registration_token
  changed_when: false
  tags:
    - gitlab_runner
    - windows_runner
    - register_runner

- name: Set gitlab_runner_token
  when:
    - gitlab_runner_token is not defined
    - runners_registration_token.stdout is defined
  set_fact:
    gitlab_runner_token: "{{ runners_registration_token.stdout }}"
  tags:
    - gitlab_runner
    - windows_runner
    - register_runner

- name: Install Gitlab runner on linux
  include_tasks: linux.yml
  when: ansible_os_family != 'Windows'
  tags:
    - gitlab_runner
    - register_runner

- name: Install Gitlab runner on windows
  include_tasks: windows.yml
  when: ansible_os_family == 'Windows'
  tags:
    - windows_runner
    - register_runner
