---

- name: Download repo installer
  get_url:
    url: https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.rpm.sh
    dest: /usr/local/bin/script.rpm.sh
    owner: root
    mode: 0700
  register: download_repo
  until: download_repo is succeeded
  retries: 3

- name: Run repo installer
  command: /usr/local/bin/script.rpm.sh
  args:
    creates: /etc/yum.repos.d/runner_gitlab-runner.repo

- name: Remove the repo installer
  file:
    path: /usr/local/bin/script.rpm.sh
    state: absent
  when: gitlab_runner_state == 'absent'
