---

- name: Download repo installer
  get_url:
    # yamllint disable-line rule:line-length
    url: https://packages.gitlab.com/install/repositories/runner/gitlab-runner/script.deb.sh
    dest: /usr/local/bin/script.deb.sh
    owner: root
    mode: 0700
  register: download_repo
  until: download_repo is succeeded
  retries: 3

- name: Run repo installer
  command: /usr/local/bin/script.deb.sh
  register: network_access
  until: network_access is success
  retries: 10
  delay: 2
  args:
    creates: /etc/apt/sources.list.d/runner_gitlab-runner.list

- name: Remove the repo installer
  file:
    path: /usr/local/bin/script.deb.sh
    state: absent
  when: gitlab_runner_state == 'absent'
