---

- name: Check for currently running runner service
  win_service:
    name: gitlab-runner
  register: service_info
  tags:
    - windows_runner

- name: Stop gitlab runner service if it is running
  win_service:
    name: gitlab-runner
    state: stopped
  when: service_info.state is defined and service_info.state == "running"
  register: service_stop
  tags:
    - windows_runner

- name: Wait for the service to stop
  win_wait_for_process:
    process_name_exact: gitlab-runner
    state: absent
    timeout: 300
  when: service_stop.changed and not ansible_check_mode
  tags:
    - skip_ansible_lint
    - windows_runner

- name: Copy new runner binary
  win_copy:
    remote_src: true
    src: C:\gitlab-runner\gitlab-runner-staging.exe
    dest: C:\gitlab-runner\gitlab-runner.exe
  notify: restart runner service
  tags:
    - windows_runner
