---

- name: Create required directories
  win_file:
    path: C:\{{ item }}
    state: directory
  loop:
    - gitlab-runner
    - gitlab-runner\cache
    - gitlab-runner\build
  tags:
    - windows_runner

- name: Get runner executable file
  win_get_url:
    # yamllint disable-line rule:line-length
    url: "https://gitlab-runner-downloads.s3.amazonaws.com/latest/binaries/gitlab-runner-windows-amd64.exe"
    dest: C:\gitlab-runner\gitlab-runner-staging.exe
  register: runner_install
  check_mode: false
  ignore_errors: true  # ExitJson with 0 arguments
  tags:
    - windows_runner

- name: Run runner install
  include_tasks: tasks-Windows.yml
  when: runner_install.changed
  tags:
    - windows_runner

- name: Check if gitlab-runner service is installed
  win_service:
    name: gitlab-runner
  register: service_info
  tags:
    - windows_runner

- name: Place runner config
  win_template:
    src: config.toml.j2
    dest: C:\gitlab-runner\config.toml
  notify: restart runner service
  tags:
    - windows_runner
    - register_runner

- name: Place powershell script
  win_template:
    src: register.ps1
    dest: C:\gitlab-runner\register.ps1
  tags:
    - windows_runner
    - register_runner

- name: Install runner service
  when: not service_info.exists
  win_command: gitlab-runner.exe install
  args:
    chdir: C:\gitlab-runner\
  tags:
    - register_runner
    - windows_runner

- name: Run all notified handlers now
  meta: flush_handlers
  tags:
    - windows_runner

# yamllint disable rule:line-length
- name: Create task to run a PS script as SYSTEM service on boot
  win_scheduled_task:
    name: Register
    description: Register Gitlab Runner
    actions:
      - path: C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe
        arguments: -ExecutionPolicy Unrestricted -NonInteractive -File C:\gitlab-runner\register.ps1
    triggers:
      - type: boot
    username: SYSTEM
    run_level: highest
    state: present

# - name: Register runner
#   win_shell: |
#     C:\gitlab-runner\register.ps1
#   args:
#     chdir: C:\gitlab-runner\
#   ignore_errors: true
#   tags:
#     - register_runner
#     - windows_runner
