---
- name: Converge
  hosts: all
  vars:
    role_name: "{{ lookup('env', 'MOLECULE_PROJECT_DIRECTORY') | basename }}"
    gitlab_transport: http
    gitlab_host: 10.1.2.4
    gitlab_port: 8080

  tasks:
    - name: "Include {{ role_name }}"
      ansible.builtin.include_role:
        name: "{{ role_name }}"
